# Generated by Django 4.2.7 on 2023-11-06 06:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0002_alter_badge_options_alter_userbadge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/models/'), upload_to='', verbose_name='Image'),
        ),
    ]
