# Generated by Django 4.2.7 on 2023-11-06 07:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0003_alter_model3d_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/models/'), upload_to='', verbose_name='Image'),
        ),
    ]
