# Generated by Django 4.2.7 on 2023-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0004_alter_model3d_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='models', verbose_name='Image'),
        ),
    ]
